name: Build Site
run-name: ${{ gitea.actor }} has started a new deploy of the website.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Explore-Gitea-Actions:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.RUNNER_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Build project
        run: npm run build
        env:
          CMS_URL: http://blog_directus:8055

      - name: Publish
        run: |
          wrangler pages deploy ./out --project-name=$PROJECT_NAME
        env:
          PROJECT_NAME: thanathan
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}